Solution8/VolleyballWebApp/Models/VolleyballDBcontext.cs
using Microsoft.EntityFrameworkCore;

namespace VolleyballWebApp.Models
{

    // context in name is a good practice for evrbdy to know it`s a relation to DB
    public class VolleyballDBcontext : DbContext

    {

        public VolleyballDBcontext(DbContextOptions<VolleyballDBcontext> options) : base(options) 
        { 
        }
    


        public DbSet<VolleyballPlayer> VolleyballPlayers { get; set; }
    }
}

Solution8/VolleyballWebApp/Models/VolleyballPlayer.cs
namespace VolleyballWebApp.Models
{
    public class VolleyballPlayer
    {

        public int Id { get; set; }
        public string Name { get; set; }
        public string Position { get; set; }
        public int Number { get; set; }
    }
}

Solution8/VolleyballWebApp/Pages/Calculator.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace VolleyballWebApp.Pages
{
    public class CalculatorModel : PageModel
    {

        public int Result { get; set; }
        public void OnGet()
        {


        }
        public void OnPost() 
        {
            var form = Request.Form;
            bool r1 = int.TryParse(form["Number1"], out int number1);  //Try creates a new var, if successful
            bool r2 = int.TryParse(form["Number2"], out int number2);


            if (r1 && r2) 
            { 
                int Result = number1 + number2; 
            }
            else
            {
                throw new Exception();
            }
            

        }
    }
}

Solution8/VolleyballWebApp/Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace VolleyballWebApp.Pages;

[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
[IgnoreAntiforgeryToken]
public class ErrorModel : PageModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

    private readonly ILogger<ErrorModel> _logger;

    public ErrorModel(ILogger<ErrorModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
        RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
    }
}

Solution8/VolleyballWebApp/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace VolleyballWebApp.Pages;

public class IndexModel : PageModel
{
    private readonly ILogger<IndexModel> _logger;

    public IndexModel(ILogger<IndexModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {

    }
}

Solution8/VolleyballWebApp/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace VolleyballWebApp.Pages;

public class PrivacyModel : PageModel
{
    private readonly ILogger<PrivacyModel> _logger;

    public PrivacyModel(ILogger<PrivacyModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
    }
}

Solution8/VolleyballWebApp/Pages/newCalculator.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace VolleyballWebApp.Pages
{
    public class newCalculatorModel : PageModel
    {

        [BindProperty]
        public int Number1 { get; set; }
        [BindProperty]
        public int Number2 { get; set; }

        [TempData] //storing data for one use
        public int AddResult { get; set; }
        [TempData]
        public int SubstractResult { get; set; }


        public void OnGet()
        {
        }

        public void OnPostAdd()
        {
            int result = Number1 + Number2;
            // the number are Binded so can calculate just like that
        }

        public void OnPostSubstract()
        {
            int result = Number1 - Number2;
            // the number are Binded so can calculate just like that
        }
    }
}

Solution8/VolleyballWebApp/Pages/volleyballPlayerList.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using VolleyballWebApp.Models;

namespace VolleyballWebApp.Pages
{
    public class volleyballPlayerListModel : PageModel
    {

        private readonly VolleyballDBcontext _context;
        // by dependency injection
        public volleyballPlayerListModel(VolleyballDBcontext context)
        {
            _context = context;
                
        }

        public List<VolleyballPlayer> VolleyballPlayers { get; set; }

        public void OnGet()
        {
            VolleyballPlayers =  _context.VolleyballPlayers.ToList();
            
        }
    }
}

Solution8/VolleyballWebApp/Pages/Calculator.cshtml
@page
@model VolleyballWebApp.Pages.CalculatorModel
@{
}


<p>This a calculator</p>


<form method="post">

    <label for="Number1">Number1</label>
    <input id="Number1" name="Number1" />
    </br>
    <label for="Number2">Number2</label>
    <input id="Number2" name="Number2" />
    </br>

    <button type="submit"> Calculate</button>

    <p> @Model.Result</p>

    



</form>

Solution8/VolleyballWebApp/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Solution8/VolleyballWebApp/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - VolleyballWebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/VolleyballWebApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">VolleyballWebApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Calculator">Calculator</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/newCalculator">Calculator</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/volleyballPlayerList">Player List</a>
                        </li>
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - VolleyballWebApp - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Solution8/VolleyballWebApp/Pages/newCalculator.cshtml
@page
@model VolleyballWebApp.Pages.newCalculatorModel
@{
}


<p>This a calculator</p>
<p>But with a binding approach</p>


<form method="post" asp-page-handler="Add">

<label for="Number1">Number1</label>
<input id="Number1" name="Number1" value="@Model.Number1"/>
    </br>
<label for="Number2">Number2</label>
<input id="Number2" name="Number2" value="@Model.Number2"/>
    </br>

<button type="submit"> Calculate</button>

<p>Result: @Model.AddResult</p>

</form>


<form method="post" asp-page-handler="Substract">

    <label for="Number1">Number1</label>
    <input id="Number1" name="Number1" value="@Model.Number1" />
    <br><br>
    <label for="Number2">Number2</label>
    <input id="Number2" name="Number2" value="@Model.Number2" />
    <br><br>

    <button type="submit"> Calculate</button>

    <p>Result: @Model.SubstractResult</p>

</form>

Solution8/VolleyballWebApp/Pages/volleyballPlayerList.cshtml
@page
@model VolleyballWebApp.Pages.volleyballPlayerListModel
@{
}


<p>Number of data : @Model.VolleyballPlayers.Count()</p>

<table>

    @foreach (var item in Model.VolleyballPlayers)
    {
        <tr>
            <td>@item.Name</td>
            <td>@item.Position</td>
            <td>@item.Number</td>
            <td>@Html.DisplayFor(modelItem=>item.Number)</td>
        </tr>
    }

</table>